
const data2 =
[
    {"mainName":"GOVERNMENT","subName":"City of Midland","item":"Administrative Service",
    "itemNum":"685-7251"},
    {"mainName":"GOVERNMENT","subName":"City of Midland", "item":"Air & Space Port,Midland International",
    "itemNum":"560-2200"},
    {"mainName":"GOVERNMENT","subName":"City of Midland", "item":"Animal Control",
                "itemNum":"685-7420"},
    {"mainName":"GOVERNMENT","subName":"City of Midland", "item":"Attorney",
                "itemNum":"685-7253"},
    {"mainName":"GOVERNMENT","subName":"City of Midland", "item":"Auditor",
                "itemNum":"685-7478"},
    {"mainName":"GOVERNMENT","subName":"City of Midland","item":"Building Inspections",
                "itemNum":"685-7390"},
    {"mainName":"GOVERNMENT","subName":"City of Midland","item":"Building Permits",
                "itemNum":"685-7390"},
    {"mainName":"GOVERNMENT","subName":"City of Midland","item":"Code Enforcement",
                "itemNum":"685-7410"},
            
    {"mainName":"GOVERNMENT","subName":"City of Midland","item":"Community Development Block Grant",
                "itemNum":"685-7472"},
    {"mainName":"GOVERNMENT","subName":"City of Midland","item":"Customer Service",
                "itemNum":"685-7320"},
    {"mainName":"GOVERNMENT","subName":"City of Midland","item":"Development Services",
                "itemNum":"685-7442"},
    {"mainName":"GOVERNMENT","subName":"City of Midland","item":"Finance & Budget",
                "itemNum":"685-7212"},
    {"mainName":"GOVERNMENT","subName":"City of Midland","item":"Fraud Hotline",
                "itemNum":"686-1658"},
    {"mainName":"GOVERNMENT","subName":"City of Midland","item":"GIS",
                "itemNum":"685-7470"},
    {"mainName":"GOVERNMENT","subName":"City of Midland","item":"Health & Senior Services",
                "itemNum":"681-7613"},
    {"mainName":"GOVERNMENT","subName":"City of Midland","item":"City Manager",
                "itemNum":"685-7202"},
    {"mainName":"GOVERNMENT","subName":"City of Midland","item":"Deputy City Manager",
                "itemNum":"685-7205"},
    {"mainName":"GOVERNMENT","subName":"City of Midland","item":"Assistant City Manager",
                "itemNum":"685-7911"},
    {"mainName":"GOVERNMENT","subName":"City of Midland","item":"Mayor & City Council",
                "itemNum":"685-7204"},
    {"mainName":"GOVERNMENT","subName":"City of Midland","item":"Municipal Court",
                "itemNum":"685-7314"},
    {"mainName":"GOVERNMENT","subName":"City of Midland","item":"Parks & Recreation",
                "itemNum":"685-7370"},
    {"mainName":"GOVERNMENT","subName":"City of Midland","item":"Planning & Zoning",
                "itemNum":"685-7400"},
    {"mainName":"GOVERNMENT","subName":"City of Midland","item":"Public Information",
                "itemNum":"685-7593"},
    {"mainName":"GOVERNMENT","subName":"City of Midland","item":"Public Safety Communication",
                "itemNum":"685-7108"},
    {"mainName":"GOVERNMENT","subName":"City of Midland","item":"Purchasing ",
                "itemNum":"685-7234"},
    {"mainName":"GOVERNMENT","subName":"City of Midland","item":"City Secretary ",
                "itemNum":"685-7430"},
    {"mainName":"GOVERNMENT","subName":"Midland County","item":"Attorney",
                "itemNum":"688-4490"},
    {"mainName":"GOVERNMENT","subName":"Midland County","item":"Auditor",
                "itemNum":"688-4860"},
    {"mainName":"GOVERNMENT","subName":"Midland County","item":"County Clerk ",
                "itemNum":"688-4401"},
    {"mainName":"GOVERNMENT","subName":"Midland County","item":"Commissioners Court ",
                "itemNum":"688-4310"},

    {"mainName":"GOVERNMENT","subName":"Constables","item":"Precinct 1",
                "itemNum":"688-4711"},
    {"mainName":"GOVERNMENT","subName":"Constables","item":"Precinct 2 ",
                "itemNum":"688-4712"},
    {"mainName":"GOVERNMENT","subName":"Constables","item":"Precinct 3 ",
                "itemNum":"688-4713"},
    {"mainName":"GOVERNMENT","subName":"Constables","item":"Precinct 4 ",
                "itemNum":"688-4701"},
    {"mainName":"GOVERNMENT","subName":"Constables","item":"Courts at Law (1 & 2) ",
                "itemNum":"688-4460"},
    {"mainName":"GOVERNMENT","subName":"Constables","item":"District Attorney ",
                "itemNum":"688-4411"},
    {"mainName":"GOVERNMENT","subName":"Constables","item":"District Clerk ",
                "itemNum":"688-4500"},
    {"mainName":"GOVERNMENT","subName":"Constables","item":"Elections",
                "itemNum":"688-4890"},
    {"mainName":"GOVERNMENT","subName":"Constables","item":"Emergency Management ",
                "itemNum":"688-4160"},
    {"mainName":"GOVERNMENT","subName":"Constables","item":"Extension Office ",
                "itemNum":"686-4700"},
    {"mainName":"GOVERNMENT","subName":"Constables","item":"Facilities Management & Planning",
                "itemNum":"688-4150"},
    {"mainName":"GOVERNMENT","subName":"Constables","item":"Fire Marshall ",
                "itemNum":"688-4160"},
    {"mainName":"GOVERNMENT","subName":"Constables","item":"Human Resources ",
                "itemNum":"688-4855"},
    {"mainName":"GOVERNMENT","subName":"Constables","item":"Information Technology ",
                "itemNum":"688-4830"},
    {"mainName":"GOVERNMENT","subName":"Constables","item":"County Judge ",
                "itemNum":"688-4310"},

    {"mainName":"GOVERNMENT","subName":"Justice of the Peace","item":"Precinct 1 ",
                "itemNum":"688-4721"},
    {"mainName":"GOVERNMENT","subName":"Justice of the Peace","item":"Precinct 2",
                "itemNum":"688-4722"},
    {"mainName":"GOVERNMENT","subName":"Justice of the Peace","item":"Precinct 3",
                "itemNum":"688-4723"},
    {"mainName":"GOVERNMENT","subName":"Justice of the Peace","item":"Precinct 4",
                "itemNum":"688-4724"},
    {"mainName":"GOVERNMENT","subName":"Justice of the Peace","item":"Library (Main) ",
                "itemNum":"688-4320"},
    {"mainName":"GOVERNMENT","subName":"Justice of the Peace","item":"Library (Centennial Branch) ",
                "itemNum":"742-7400"},
    {"mainName":"GOVERNMENT","subName":"Justice of the Peace","item":"Purchasing",
                "itemNum":"688-4870"},
    {"mainName":"GOVERNMENT","subName":"Justice of the Peace","item":"Road & Bridge ",
                "itemNum":"688-4155"},
    {"mainName":"GOVERNMENT","subName":"Justice of the Peace","item":"Tax Assessor & Collector ",
                "itemNum":"688-4810"},
    {"mainName":"GOVERNMENT","subName":"Justice of the Peace","item":"Treasurer",
                "itemNum":"688-4880"},

    {"mainName":"RESCUE & LAW ENFORCEMENT","subName":"","item":"Emergency (fire, police, sheriff, ambulance) ",
                "itemNum":"911"},
    {"mainName":"RESCUE & LAW ENFORCEMENT","subName":"","item":"Midland County Sheriff’s Department (non-emergency) ",
                "itemNum":"688-4600"},
    {"mainName":"RESCUE & LAW ENFORCEMENT","subName":"","item":"Midland Crime Stoppers ",
                "itemNum":"694-8477"},
    {"mainName":"RESCUE & LAW ENFORCEMENT","subName":"","item":"Midland FBI (non-emergency) ",
                "itemNum":"570-0255"},
    {"mainName":"RESCUE & LAW ENFORCEMENT","subName":"","item":"Midland Fire Department (non-emergency) ",
                "itemNum":"685-7436"},
    {"mainName":"RESCUE & LAW ENFORCEMENT","subName":"","item":"Midland Highway Patrol (non-emergency) ",
                "itemNum":"498-2140"},
    {"mainName":"RESCUE & LAW ENFORCEMENT","subName":"","item":"Midland Police Department (non-emergency) ",
                "itemNum":"685-7110"},
    {"mainName":"RESCUE & LAW ENFORCEMENT","subName":"","item":"U.S. Marshal (non-emergency) ",
                "itemNum":"686-4100"},

    {"mainName":"COMMUNITY SERVICES","subName":"","item":"Able Center for Independent Living ",
                "itemNum":"580-3439"},
    {"mainName":"COMMUNITY SERVICES","subName":"","item":"Midland Chamber of Commerce",
                "itemNum":"683-3381"},
    {"mainName":"COMMUNITY SERVICES","subName":"","item":"Midland Memorial Hospital ",
                "itemNum":"221-1111"},
    {"mainName":"COMMUNITY SERVICES","subName":"","item":"National Weather Service Forecast Office ",
                "itemNum":"563-5006"},
    {"mainName":"COMMUNITY SERVICES","subName":"","item":"Social Security ",
                "itemNum":"(866) 404-1866"},
    {"mainName":"COMMUNITY SERVICES","subName":"","item":"Texas Information & Referral Inside Texas ",
                "itemNum":"211"},
    {"mainName":"COMMUNITY SERVICES","subName":"","item":"Outside Texas ",
                "itemNum":"(877) 541-7905"},
    {"mainName":"COMMUNITY SERVICES","subName":"","item":"Time, Temperature & Weather ",
                "itemNum":"563-9292"},
    {"mainName":"COMMUNITY SERVICES","subName":"","item":"Workforce Solutions PB/Midland ",
                "itemNum":"686-4879"},

    {"mainName":"UTILITIES","subName":"","item":"Oncor (Electric Delivery) ",
                "itemNum":"(888) 313-6862"},
    {"mainName":"UTILITIES","subName":"","item":"Reliant, an NRG company ",
                "itemNum":"(866) 222-7100"},
    {"mainName":"UTILITIES","subName":"","item":"TXU Energy Gas",
                "itemNum":"(800) 818-6132"},
    {"mainName":"UTILITIES","subName":"","item":"Atmos Energy ",
                "itemNum":"(866) 286-6700"},
    {"mainName":"UTILITIES","subName":"","item":"Emergency",
                "itemNum":"(866) 322-8667"},
    {"mainName":"UTILITIES","subName":"","item":"Water & Sewer City of Midland Utilities ",
                "itemNum":"685-7262"},
    {"mainName":"UTILITIES","subName":"","item":"Customer Service/Bill Pay Trash",
                "itemNum":"685-7320"},
    {"mainName":"UTILITIES","subName":"","item":"City of Midland Solid Waste ",
                "itemNum":"685-7278"},
    {"mainName":"UTILITIES","subName":"","item":"Republic Services ",
                "itemNum":"561-7600"},
    {"mainName":"UTILITIES","subName":"","item":"Cable/Digital Television Grande Communications ",
                "itemNum":"272-3000"},
    {"mainName":"UTILITIES","subName":"","item":"Suddenlink Communications Internet Service ",
                "itemNum":"694-7721"},
    {"mainName":"UTILITIES","subName":"","item":"Grande Communications ",
                "itemNum":"272-3040"},
    {"mainName":"UTILITIES","subName":"","item":"Suddenlink Communications Telephone ",
                "itemNum":"694-7721"},
    {"mainName":"UTILITIES","subName":"","item":"Petro Communications, Inc ",
                "itemNum":"683-4786"},

    {"mainName":"NEWSPAPER","subName":"","item":"Midland Reporter-Telegram ",
                "itemNum":"682-5311"},

    {"mainName":"POSTAL SERVICES","subName":"","item":"General Mail Facility10000 Loop 40, 79711-9998 ",
                "itemNum":"560-5105"},
    {"mainName":"POSTAL SERVICES","subName":"","item":"Claydesta Station 612 Veterans Airpark Ln., 79705-9998 ",
                "itemNum":"687-5961"},
    {"mainName":"POSTAL SERVICES","subName":"","item":"Downtown Branch 100 E. Wall Ave., 79701-9998 ",
                "itemNum":"682-3381"},
    {"mainName":"POSTAL SERVICES","subName":"","item":"Graves Branch 3304 W. Wadley, 79707-9998 ",
                "itemNum":"694-9546"},
    {"mainName":"POSTAL SERVICES","subName":"","item":"Village Branch 2315 W. Louisiana, 79701-9997",
                "itemNum":"683-5461"},


    {"mainName":"VEHICLES","subName":"","item":"Drivers License 2800 Wright Dr. Midland, TX 79703 ",
                "itemNum":"686-1120"},
    {"mainName":"VEHICLES","subName":"","item":"Titles & Registration Midland County Tax Office 2110 N. A St., Ste. 111, Midland ",
                "itemNum":"688-4810"}
            ];
        
export default data2